# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run:
         name: List current directory
         command: |
            sudo chmod -R 777 ~
            ls -la

      - run:
         name: Update and Install dependencies
         command: |
            sudo apt-get update
            sudo apt-get install python-wxgtk2.8
            sudo pip install Sphinx

      - run:
         name: Create python package
         command: sudo python setup.py bdist_wheel

      - run:
         name: Install python package
         command: |
            cd dist
            sudo python -m pip install wxpy_mvc-0.1-py3-none-any.whl
            sudo pip list
            cd ..

      - run:
         name: Create Sphinx documentation
         command: |
            cd sphinx_source
            sphinx-build -b html . ../docs

      - run:
         name: Run demo script
         command: |
            cd demo
            sudo chmod +x demo.py
            sudo ./demo.py
