# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
   build:
      working_directory: ~/wxpy-mvc
      docker:
         - image: circleci/python:latest
      steps:
         - checkout

        - run:
           name: List current directory
           command: ls -la
#            name: Update and Install dependencies
#            command: |
#               apt-get update
#               #apt-get install -y pip
