# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run:
         name: List current directory
         command: ls -la

      - run:
         name: Create python package
         command: python setup.py bdist_wheel

      - run:
         name: Install python package
         command: |
            cd dist
            python -m pip install wxpy_mvc-0.1-py3-none-any.whl
            cd ..
#            name: Update and Install dependencies
#            command: |
#               apt-get update
#               #apt-get install -y pip
